<?php

namespace EdwinLuijten\Houston\Tests;

use EdwinLuijten\Houston\Houston;

class HoustonTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $_SESSION = [];
    }

    public function testThatErrorIsLogged()
    {


        throw new \Exception('weoo');
    }
}